const excelToXMLMap = {
    "Parent EIDR/Row ID": "ID",
    "Structural Type": "StructuralType",
    "Referent Type": "ReferentType",
    "Title": "ResourceName",
    "Release Date": "ReleaseDate",
    "Approximate Length": "ApproximateLength",
    "Actor 1:": "Actor",
    "Actor 2:": "Actor",
    "Actor 3:": "Actor",
    "Actor 4:": "Actor",
    "Director 1": "Director",
    "Director 2": "Director",

    "Title Language": "TitleLanguage",
    "Title Class": "TitleClass",
    "Original Language 1": "OriginalLanguage1",
    "Language Mode 1": "LanguageMode1",
    "Alternate Title 1": "AlternateTitle1",
    "Alt Title Language 1": "AltTitleLanguage1",
    "Alt Title Class 1": "AltTitleClass1",
    "Alternate Title 2": "AlternateTitle2",
    "Alt Title Language 2": "AltTitleLanguage2",
    "Alt Title Class 2": "AltTitleClass2",
    "Country of Origin 1": "CountryOfOrigin1",
    "Associated Org 1": "AssociatedOrg1",
    "Associated Org Role 1": "AssociatedOrgRole1",
    "Associated Org Party ID 1": "AssociatedOrgPartyID1",
    "Associated Org 2": "AssociatedOrg2",
    "Associated Org Role 2": "AssociatedOrgRole2",
    "Associated Org Party ID 2": "AssociatedOrgPartyID2",
    "Associated Org 3": "AssociatedOrg3",
    "Associated Org Role 3": "AssociatedOrgRole3",
    "Associated Org Party ID 3": "AssociatedOrgPartyID3",
    "Metadata Authority 1": "MetadataAuthority1",
    "Metadata Authority Party ID 1": "MetadataAuthorityPartyID1",
    "Release Date": "ReleaseDate",
    "End Date": "EndDate",
    "Time Slot": "TimeSlot",
    "Series Class": "SeriesClass",
    "Season Class 1": "SeasonClass1",
    "Episode Class 1": "EpisodeClass1",
    "Number Required": "NumberRequired",
    "Date Required": "DateRequired",
    "Original Title Required": "OriginalTitleRequired",
    "Season No.": "SeasonNo.",
    "Distribution No.": "DistributionNo.",
    "Dist. No. Domain": "Dist.No.Domain",
    "House No.": "HouseNo.",
    "House No. Domain": "HouseNo.Domain",
    "Alternate No. 1": "AlternateNo.1",
    "Alt. No. Domain 1": "Alt.No.Domain1",
    "Publication Status": "PublicationStatus",
    "Approx Length": "ApproxLength",
    "Registrant": "Registrant",
    "Director 1": "Director1",
    "Director 2": "Director2",
    "Actor 1": "Actor1",
    "Actor 2": "Actor2",
    "Actor 3": "Actor3",
    "Actor 4": "Actor4",
    "Alt ID 1": "AltID1",
    "Domain 1": "Domain1",
    "Relation 1": "Relation1",
    "Alt ID 2": "AltID2",
    "Domain 2": "Domain2",
    "Relation 2": "Relation2",
    "Alt ID 3": "AltID3",
    "Domain 3": "Domain3",
    "Relation 3": "Relation3",
    "IMDb": "IMDb",
    "IMDb Relation": "IMDbRelation",
    "ISAN": "ISAN",
    "ISAN Relation": "ISANRelation",
    "Description": "Description",
    "Description Language": "DescriptionLanguage",
    "Registrant Extra": "RegistrantExtra",
    "Operator's Notes": "Operator'sNotes",
    "Assigned EIDR ID": "AssignedEIDRID",
    "Registration Errors & Notes": "RegistrationErrors&Notes"
};

export default excelToXMLMap;